In [1]:
import pandas as pd

In [2]:
film_set = pd.read_csv("film_df.csv")
film_set.head()

,tconst,titleType,primaryTitle,startYear,runtimeMinutes,genres,averageRating,numVotes,title,region,language,isOriginalTitle,english_grammar_signal,era,log_numVotes
0,tt0069204,movie,Sabse Bada Sukh,1972,114.0,"Comedy,Drama",6.0,21,Subse Bada Sukh,IN,bn,0,False,Classics,1.342423
1,tt0070047,movie,The Exorcist,1973,122.0,Horror,8.1,493902,The Exorcist,IN,bn,0,True,Classics,5.693642
2,tt0070047,movie,The Exorcist,1973,122.0,Horror,8.1,493902,Shoitan Raat,IN,bn,0,True,Classics,5.693642
3,tt0073191,movie,Jai Santoshi Maa,1975,145.0,"Drama,Fantasy",6.6,242,Joy Sontoshi Maa,IN,bn,0,False,Classics,2.385606
4,tt0078170,movie,Roads to the South,1978,100.0,Drama,5.5,291,Putevi na Jug,BD,bn,0,True,Classics,2.465383

In [3]:
film_set[['startYear', 'era', 'numVotes', 'log_numVotes']].describe()

         startYear      numVotes  log_numVotes
count   269.000000  2.690000e+02    269.000000
mean   2005.721190  5.062871e+04      2.668803
std      15.532836  1.760129e+05      1.380119
min    1970.000000  6.000000e+00      0.845098
25%    1992.000000  3.300000e+01      1.531479
50%    2011.000000  2.500000e+02      2.399674
75%    2018.000000  2.188000e+03      3.340246
max    2025.000000  1.670175e+06      6.222762